-- -- ctrlp configuration
-- vim.g.ctrlp_user_command = { '.git', 'cd %s && git ls-files -co --exclude-standard' }
-- 
-- vim.g.ctrlp_custom_ignore = {
--   dir = [[\v[\/](\.git|\.hg|\.svn|build|dist|target)$]],
--   file = [[\v\.(exe|so|dll)$]],
-- }
-- 
-- -- Map <leader>b to :CtrlPBuffer
-- vim.keymap.set('n', '<leader>b', ':CtrlPBuffer<CR>', { noremap = true, silent = true })
-- 
-- -- Ack/Ag settings
-- if vim.fn.executable('ag') == 1 then
--   vim.g.ackprg = 'ag --nogroup --nocolor --column'
-- end
-- 
