#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# ==================================================
# ENVIRONMENT SETTINGS
# ==================================================
export SCALA_HOME=/usr/local/scala/scala
export SBT_HOME=/usr/local/scala/sbt
export PATH=$PATH:$SCALA_HOME/bin:$SBT_HOME/bin

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
# export PATH="$PATH:$HOME/libs/vert.x/bin"
# export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/Qt/5.4/gcc_64/lib/cmake

# DisCODe installation
export DISCODE_DCL_DIR=/home/$USER/src/DCL
export PATH=$PATH:/home/$USER/bin/DisCODe/bin

# GMock location
export GMOCK_HOME=~/libs/gmock

# cURL
export CURL_HOME=~/libs/curl

# JsonCpp
export JSONCPP_HOME=~/libs/jsoncpp

# Postgres slony
export CLUSTERNAME=slony_example
export MASTERDBNAME=pgbench
export SLAVEDBNAME=pgbenchslave
export MASTERHOST=localhost
export SLAVEHOST=localhost
export REPLICATIONUSER=postgres
export PGBENCHUSER=pgbench


export JBOSS_HOME=/home/$USER/libs/syncron-wildfly-9.0.2.final/jboss-as
