session_name: config
windows:
- window_name: zsh
  focus: 'true'
  options: {}
  panes:
  - focus: 'true'
    shell_command: 
  start_directory: $HOME
- window_name: dotfiles
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvim
  start_directory: $HOME/qiubix-settings/zsh
