#!/usr/bin/env bash
#
# Configure default/conditional Git identities and personal/work SSH aliases.
#
# Repositories below WORK_ROOT and PERSONAL_ROOT use their matching identity.
# The selected default applies outside both roots. SSH remotes use:
#   git@github.com-personal:OWNER/REPO.git
#   git@gitlab.com-personal:NAMESPACE/REPO.git
#   git@github.com-work:ORG/REPO.git
#   git@gitlab.com-work:NAMESPACE/REPO.git

set -euo pipefail

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
local_config="$HOME/.gitconfig.local"
personal_config="$HOME/.gitconfig.personal"
work_config="$HOME/.gitconfig.work"
ssh_config="$HOME/.ssh/config"

prompt() {
  local label="$1" default="$2" output_var="$3" env_var="$4" value
  if [[ -n "${!env_var:-}" ]]; then
    printf -v "$output_var" '%s' "${!env_var}"
    return
  fi
  read -r -p "$label [$default]: " value
  printf -v "$output_var" '%s' "${value:-$default}"
}

prompt "Personal name" "${GIT_PERSONAL_NAME:-qiubix}" personal_name GIT_PERSONAL_NAME
prompt "Personal email" "${GIT_PERSONAL_EMAIL:-qiubix@gmail.com}" personal_email GIT_PERSONAL_EMAIL
prompt "Work name" "${GIT_WORK_NAME:-Your Work Name}" work_name GIT_WORK_NAME
prompt "Work email" "${GIT_WORK_EMAIL:-work@example.com}" work_email GIT_WORK_EMAIL
prompt "Work repository root" "${GIT_WORK_ROOT:-$HOME/work}" work_root GIT_WORK_ROOT
prompt "Personal repository root" "${GIT_PERSONAL_ROOT:-$HOME/code}" personal_root GIT_PERSONAL_ROOT
prompt "Default identity (personal/work)" "${GIT_DEFAULT_IDENTITY:-personal}" default_identity GIT_DEFAULT_IDENTITY

case "$default_identity" in
  personal|work) ;;
  *)
    echo "Default identity must be 'personal' or 'work': $default_identity" >&2
    exit 1
    ;;
esac

if [[ -z "$personal_name" || -z "$personal_email" || -z "$work_name" ||
  -z "$work_email" || -z "$work_root" || -z "$personal_root" ]]; then
  echo "All Git identity values and repository roots are required." >&2
  exit 1
fi

mkdir -p "$work_root"
work_root="$(cd "$work_root" 2>/dev/null && pwd -P || true)"
if [[ -z "$work_root" ]]; then
  echo "Work repository root does not exist: ${GIT_WORK_ROOT:-$HOME/work}" >&2
  exit 1
fi
mkdir -p "$personal_root"
personal_root="$(cd "$personal_root" 2>/dev/null && pwd -P || true)"
if [[ -z "$personal_root" ]]; then
  echo "Personal repository root does not exist: ${GIT_PERSONAL_ROOT:-$HOME/code}" >&2
  exit 1
fi

mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

cat >"$personal_config" <<EOF
# Generated by $dotfiles_dir/scripts/setup-git.sh. Do not commit this file.
[user]
	name = $personal_name
	email = $personal_email
EOF
chmod 600 "$personal_config"

cat >"$work_config" <<EOF
# Generated by $dotfiles_dir/scripts/setup-git.sh. Do not commit this file.
[user]
	name = $work_name
	email = $work_email
EOF
chmod 600 "$work_config"

# Preserve safe.directory entries while replacing the generated identity and
# conditional include configuration.
safe_directories=()
if [[ -f "$local_config" ]]; then
  while IFS= read -r directory; do
    [[ -n "$directory" ]] && safe_directories+=("$directory")
  done < <(git config --file "$local_config" --get-all safe.directory 2>/dev/null || true)
fi
{
  cat <<EOF
# Generated by $dotfiles_dir/scripts/setup-git.sh. Do not commit this file.
[include]
	path = ~/.gitconfig.$default_identity

[includeIf "gitdir:$work_root/**"]
	path = ~/.gitconfig.work

[includeIf "gitdir:$personal_root/**"]
	path = ~/.gitconfig.personal
EOF
  if ((${#safe_directories[@]})); then
    for directory in "${safe_directories[@]}"; do
      printf '\n[safe]\n\tdirectory = %s\n' "$directory"
    done
  fi
} >"$local_config"
chmod 600 "$local_config"

configure_key() {
  local key_file="$1" comment="$2"
  if [[ ! -f "$key_file" ]]; then
    ssh-keygen -t ed25519 -C "$comment" -f "$key_file"
  fi
  chmod 600 "$key_file"
  chmod 644 "$key_file.pub"
}

configure_key "$HOME/.ssh/id_ed25519_github_personal" "$personal_email"
configure_key "$HOME/.ssh/id_ed25519_gitlab_personal" "$personal_email"
configure_key "$HOME/.ssh/id_ed25519_work" "$work_email"

tmp_ssh_config="$(mktemp)"
if [[ -f "$ssh_config" ]]; then
  awk '
    /^# BEGIN qiubix( personal)? git hosts$/ { skip=1; next }
    /^# END qiubix( personal)? git hosts$/ { skip=0; next }
    !skip { print }
  ' "$ssh_config" >"$tmp_ssh_config"
fi
cat >>"$tmp_ssh_config" <<EOF

# BEGIN qiubix git hosts
Host github.com-personal
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_ed25519_github_personal
	IdentitiesOnly yes

Host gitlab.com-personal
	HostName gitlab.com
	User git
	IdentityFile ~/.ssh/id_ed25519_gitlab_personal
	IdentitiesOnly yes

Host github.com-work
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_ed25519_work
	IdentitiesOnly yes
# END qiubix git hosts
EOF
install -m 600 "$tmp_ssh_config" "$ssh_config"
rm -f "$tmp_ssh_config"

echo
echo "Git identities configured:"
echo "  default:  $default_identity"
echo "  personal: $personal_name <$personal_email> under $personal_root"
echo "  work:     $work_name <$work_email> under $work_root"
echo
echo "Add these public keys to the matching accounts:"
echo "  GitHub:  $HOME/.ssh/id_ed25519_github_personal.pub"
echo "  GitLab:  $HOME/.ssh/id_ed25519_gitlab_personal.pub"
echo "  Work:    $HOME/.ssh/id_ed25519_work.pub"
echo
echo "Personal remote examples:"
echo "  git@github.com-personal:OWNER/REPO.git"
echo "  git@gitlab.com-personal:NAMESPACE/REPO.git"
echo
echo "Work SSH remote examples:"
echo "  git@github.com-work:ORG/REPO.git"
echo "  git@gitlab.com-work:NAMESPACE/REPO.git"
echo
echo "For work HTTPS credentials, run: gh auth login && gh auth setup-git"
